export const arkansasCareers = {
  highSchoolDiploma: [
    { title: "Electricians", workers: 8600, outlook: "A", wage: 49420 },
    { title: "Carpenters", workers: 4872, outlook: "A", wage: 46320 },
    { title: "Chefs and Head Cooks", workers: 10465, outlook: "A", wage: 40060 },
    { title: "Child Care Workers", workers: 10465, outlook: "A", wage: 27160 },
    { title: "Automotive Body and Related Repairers", workers: 1315, outlook: "AA", wage: 47230 },
    { title: "Home Health and Personal Care Aides", workers: 20701, outlook: "AA", wage: 27110 },
    { title: "Brickmasons and Blockmasons", workers: 444, outlook: "AA", wage: 48100 },
    { title: "Construction and Building Inspectors", workers: 1177, outlook: "D", wage: 52970 },
    { title: "Food Service Managers", workers: 4610, outlook: "A", wage: 53880 },
    { title: "Police and Sheriffs Patrol Officers", workers: 5413, outlook: "A", wage: 48090 },
    { title: "Plumbers, Pipefitters and Steamfitters", workers: 111, outlook: "BA", wage: 49700 },
    { title: "Postal Service Clerks", workers: 1021, outlook: "D", wage: 58940 },
    { title: "Real Estate Sales Agents", workers: 2479, outlook: "A", wage: 38450 },
    { title: "Recreation Workers", workers: 1579, outlook: "AA", wage: 26520 },
    { title: "Security Guards", workers: 8367, outlook: "A", wage: 37000 },
    { title: "Sheet Metal Workers", workers: 915, outlook: "A", wage: 42640 },
    { title: "Welding, Soldering and Brazing Workers", workers: null, outlook: "A", wage: null },
    { title: "Farm Equipment Mechanics and Service Technicians", workers: 1148, outlook: "A", wage: 47720 },
    { title: "Millwrights", workers: 831, outlook: "A", wage: 50510 },
  ],
  associateDegree: [
    { title: "Dental Hygienists", workers: 1023, outlook: "A", wage: 83760 },
    { title: "Cardiovascular Technologists and Technicians", workers: 345, outlook: "A", wage: 70930 },
    { title: "Occupational Therapy Assistants", workers: 527, outlook: "AA", wage: 77340 },
    { title: "Physical Therapist Assistants", workers: 1466, outlook: "AA", wage: 67230 },
    { title: "Respiratory Therapists", workers: 1563, outlook: "A", wage: 67960 },
    { title: "Radiologic Technologists and Technicians", workers: 2481, outlook: "BA", wage: 60430 },
    { title: "Diagnostic Medical Sonographers", workers: 458, outlook: "A", wage: 78500 },
    { title: "Paralegal and Legal Assistants", workers: 2188, outlook: "BA", wage: 46940 },
    { title: "Air Traffic Controllers", workers: 236, outlook: "BA", wage: 99490 },
    { title: "Architectural and Civil Drafters", workers: 1001, outlook: "A", wage: 60390 },
    { title: "Computer Network Support Specialists", workers: 1350, outlook: "A", wage: 58790 },
    { title: "Agricultural Technicians", workers: 447, outlook: "A", wage: 43950 },
    { title: "Chemical Technicians", workers: 575, outlook: "A", wage: 46720 },
    { title: "Electrical and Electronics Engineering Technologists", workers: 325, outlook: "BA", wage: 70340 },
    { title: "Nuclear Medicine Technologists", workers: 149, outlook: "BA", wage: 75150 },
    { title: "Human Resources Assistants", workers: 654, outlook: "BA", wage: 44850 },
    { title: "Veterinary Technologists and Technicians", workers: 203, outlook: "AA", wage: 34880 },
    { title: "Funeral Home Managers", workers: 445, outlook: "A", wage: 57980 },
    { title: "Food Science Technicians", workers: 226, outlook: "D", wage: 46400 },
    { title: "Preschool Teachers (except special education)", workers: 4491, outlook: "AA", wage: 36050 },
  ],
  bachelorsDegree: [
    { title: "Registered Nurses", workers: 29290, outlook: "A", wage: 77130 },
    { title: "Software Developers", workers: 5543, outlook: "AA", wage: 96820 },
    { title: "Information Security Analysts", workers: 961, outlook: "AA", wage: 93560 },
    { title: "Data Scientists", workers: 275, outlook: "AA", wage: 104320 },
    { title: "Marketing Managers", workers: 1264, outlook: "A", wage: 127320 },
    { title: "Sales Managers", workers: 2275, outlook: "BA", wage: 119990 },
    { title: "Computer and Information Systems Managers", workers: 3449, outlook: "A", wage: 118230 },
    { title: "Computer Systems Analysts", workers: 2598, outlook: "A", wage: 72540 },
    { title: "Database Administrators", workers: 494, outlook: "A", wage: 79710 },
    { title: "Computer Network Architects", workers: 745, outlook: "A", wage: 109900 },
    { title: "Elementary School Teachers", workers: 12755, outlook: "A", wage: 50550 },
    { title: "Middle School Teachers", workers: 6083, outlook: "A", wage: 56980 },
    { title: "Secondary School Teachers", workers: 12390, outlook: "A", wage: 56890 },
    { title: "Social Workers", workers: 1180, outlook: "BA", wage: 46210 },
    { title: "Substance Abuse and Mental Health Counselors", workers: 2518, outlook: "AA", wage: 49990 },
    { title: "Accountants and Auditors", workers: 8760, outlook: "A", wage: 64180 },
    { title: "Financial Managers", workers: 7119, outlook: "A", wage: 103410 },
    { title: "Human Resources Managers", workers: 1292, outlook: "A", wage: 99760 },
    { title: "Project Management Specialists", workers: 5059, outlook: "A", wage: 81970 },
    { title: "Public Relations Managers", workers: 459, outlook: "A", wage: 140970 },
    { title: "Electrical Engineers", workers: 867, outlook: "A", wage: 96500 },
    { title: "Civil Engineers", workers: 2072, outlook: "A", wage: 81930 },
    { title: "Environmental Engineers", workers: 178, outlook: "A", wage: 84600 },
    { title: "Industrial Engineers", workers: 2022, outlook: "A", wage: 94184 },
    { title: "Mechanical Engineers", workers: 1032, outlook: "BA", wage: 78570 },
    { title: "Architects", workers: 978, outlook: "BA", wage: 84310 },
    { title: "Dietitians and Nutritionists", workers: 854, outlook: "A", wage: 60740 },
    { title: "Recreational Therapists", workers: 60, outlook: "BA", wage: 45060 },
    { title: "Occupational Health and Safety Specialists", workers: 763, outlook: "A", wage: 71570 },
    { title: "Social and Community Service Managers", workers: 2114, outlook: "AA", wage: 53360 },
    { title: "Natural Sciences Managers", workers: 310, outlook: "BA", wage: 134430 },
    { title: "Medical and Health Services Managers", workers: 6813, outlook: "AA", wage: 88340 },
    { title: "Web Developers", workers: 554, outlook: "AA", wage: 43530 },
    { title: "Web and Digital Interface Designers", workers: 692, outlook: "A", wage: 57020 },
    { title: "Graphic Designers", workers: 1675, outlook: "BA", wage: 46430 },
    { title: "Writers and Authors", workers: 575, outlook: "BA", wage: 46490 },
    { title: "Logisticians", workers: 1562, outlook: "AA", wage: 73710 },
    { title: "Management Analysts", workers: 6748, outlook: "A", wage: 72550 },
    { title: "Training and Development Managers", workers: 258, outlook: "A", wage: 90890 },
    { title: "Network and Computer Systems Administrators", workers: 1610, outlook: "A", wage: 79040 },
    { title: "Chief Executives", workers: 3022, outlook: "BA", wage: 121220 },
    { title: "Personal Financial Advisors", workers: 2208, outlook: "AA", wage: 75150 },
  ],
  outlookLabels: {
    AA: "Above Average (5%+ job growth)",
    A: "Average (2-5% job growth)",
    BA: "Below Average (0-2% job growth)",
    D: "Declining (negative job growth)",
  },
};
